name: "Bot: Send Close Pull Request Signal"

on:
  pull_request:
    types:
      [closed]

# Deny all permissions by default
permissions: {}

jobs:
  send-close-signal:
    name: "Send closing signal"
    runs-on: ubuntu-22.04
    if: ${{ github.event.action == 'closed' }}
    steps:
      - name: "Create PRtifact"
        run: |
          mkdir -p ./pr
          printf ${{ github.event.number }} > ./pr/NUM
      - name: Upload Diff
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
          name: pr
          path: ./pr
