name: "01 Build and Deploy Site"

on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '0 0 * * 2'
  workflow_dispatch:
    inputs:
      name:
        description: 'Who triggered this build?'
        required: true
        default: 'Maintainer (via GitHub)'
      reset:
        description: 'Reset cached markdown files'
        required: false
        default: false
        type: boolean

# Deny all permissions by default
permissions: {}

jobs:
  full-build:
    name: "Build Full Site"

    # 2024-10-01: ubuntu-latest is now 24.04 and R is not installed by default in the runner image
    # pin to 22.04 for now
    runs-on: ubuntu-22.04
    permissions:
      checks: write
      contents: write
      pages: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_PATHS_ROOT: ~/.local/share/renv/
    steps:

      - name: "Checkout Lesson"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      - name: "Set up R"
        uses: r-lib/actions/setup-r@f9a764fea8d5c63df6ef9a5c7795bf7deb5d7e05  # v2
        with:
          use-public-rspm: true
          install-r: false

      - name: "Set up Pandoc"
        uses: r-lib/actions/setup-pandoc@f9a764fea8d5c63df6ef9a5c7795bf7deb5d7e05  # v2

      - name: "Setup Lesson Engine"
        uses: carpentries/actions/setup-sandpaper@24898f898388e129d2bbc1f2d8634d7f79cc356b  # v1.0.0
        with:
          cache-version: ${{ secrets.CACHE_VERSION }}

      - name: "Setup Package Cache"
        uses: carpentries/actions/setup-lesson-deps@24898f898388e129d2bbc1f2d8634d7f79cc356b  # v1.0.0
        with:
          cache-version: ${{ secrets.CACHE_VERSION }}

      - name: "Deploy Site"
        run: |
          reset <- "${{ github.event.inputs.reset }}" == "true"
          sandpaper::package_cache_trigger(TRUE)
          sandpaper:::ci_deploy(reset = reset)
        shell: Rscript {0}
